title: Blog technique de Decitre
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Le blog des Ã©quipes techniques de Decitre
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.decitre.fr"
twitter_username: Decitre
github_username: Decitre-Interactive

comment_repository: Decitre-Interactive/decitre-interactive.github.io
git_branch: master

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
 - docker-compose.*
 - docker
 - tools
 - README.md
 - Makefile
 - composer.phar

recaptcha_enabled: true
recaptcha_site_key: "6LdnITgUAAAAAKcUC9X_vkUV00HZoL-lRmXBdem3"
recaptcha_staticman_secret: "EdNGgrH2Z49qTXGtXKUt8OE/mGkmxUHA1jGu1MdNSRufaf8VFrX03R6VHK2KUHxxe4Bhp2FCHpfgusT1av1rFjT3v3LN+HCbOpf/9p/Cl+hghw2l+DfZEYK6fc966tM8LL6tS1lwMYAotxFcB4tTenUrGNEpR9hBgHJ+A2+R4VY="
