title: Blog technique de Decitre
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Le blog des Ã©quipes techniques de Decitre
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tech.decitre.fr"
twitter_username: Decitre
github_username: Decitre-Interactive

comment_repository: Decitre-Interactive/decitre-interactive.github.io
git_branch: master

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed

exclude:
 - docker-compose.*
 - docker
 - tools
 - README.md
 - Makefile
 - composer.phar
